Importing dependencies

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import tensorflow as tf
tf.random.set_seed(3)            # used for generating same random values  of weights and bias during initialization during every run
from tensorflow import keras
from keras.datasets import mnist
from tensorflow.math import confusion_matrix


 Loading image data from MNIST

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
for i in range(2):
  print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

In [ ]:
cv2_imshow(x_train[10])
print(y_train[10])

3


scaling the data

```
# This is formatted as code
```



In [ ]:
x_train = x_train/255
x_test = x_test/255
t_train = x_train.reshape(60000,28*28,-1)
t_train.shape

(60000, 784, 1)

In [ ]:
print(t_train[0])

Building the neural network

In [ ]:
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28,28)), # as each element of training set is a 2_d array , we cannot feed 2-d data to neural network. flatten converts it to 1-d array
                          keras.layers.Dense(units = 50, activation = 'relu'),
                          keras.layers.Dense(units = 50 , activation = 'relu'),
                          keras.layers.Dense(units = 10, activation = 'softmax')


])
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ['accuracy']
)

Training the model

In [ ]:
model.fit(x_train,y_train,epochs =10)

Training data accuracy is 99%

In [ ]:
print(x_train[10])

In [ ]:
loss , accuracy = model.evaluate(x_test,y_test)

In [ ]:
y_pred = model.predict(x_test)

313/313 [==============================] - 1s 1ms/step


In [ ]:
print(y_pred.shape)

(10000, 10)


In [ ]:
print(y_pred[0])

[2.05516537e-09 3.57602130e-06 2.30742012e-06 2.46911304e-06
 1.79798718e-10 1.27501798e-09 1.58325620e-14 9.99991477e-01
 1.38308005e-08 1.00037518e-07]


Converting the prediction probability to labels

In [ ]:
y_pred_labels = [np.argmax(i) for i in y_pred]

predicting for single imagw
Here the neural network expects to take inputs of multiple images
to make the system predict for 3 images , we have to reshape the image

In [ ]:
x_single = np.reshape(x_test[7], [1,28,28])   # here 1 denotes a single input

In [ ]:
y_single = model.predict(x_single)

1/1 [==============================] - 0s 17ms/step


In [ ]:
print(y_single)

[[8.9074052e-12 2.0025045e-07 2.4346716e-04 1.8747924e-05 3.6072531e-03
  1.9383493e-10 5.7312138e-15 3.4061057e-07 5.4635507e-07 9.9612939e-01]]


In [ ]:
y_single_label = np.argmax(y_single)
print(y_single_label)

9


In [ ]:
print(y_test[7])

9
